DEBUG = True

# Flask settings
JSONIFY_PRETTYPRINT_REGULAR	= False

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# SQL Alchemy config
SQLALCHEMY_TRACK_MODIFICATIONS = False
